version: "3"
services:
  node:
    build: .
    container_name: banco-backend
    tty: true
    stdin_open: true
    command: sh
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    env_file: .env
    environment:
      MYSQLHOST: banco_db
  db:
    image: mysql:8.0.32
    container_name: acelera_db
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}
networks:
  default:
    name: banco_net